# Generated by Django 5.0.7 on 2024-09-06 14:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_updated_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 6, 14, 24, 16, 776084, tzinfo=datetime.timezone.utc)),
        ),
    ]
